# Generated by Django 3.0.3 on 2025-10-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='embeddings',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
